### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ivann47** [ivalan72/DayHLNG#2]

**Comment by ivalan72** [comment]
World!

**Comment by ivann47** [comment]
Дополнение к роботу:

если открыты две позиции и отложки не выставляются И
если прошли сутки после открытия второй позиции и реверсные больше не могут открыться И
если обе позиции одного направления ( обе buy ИЛИ обе sell) И
если сумма убытков по обеим позициям больше значения фиксированного SL, ТО
позиция с большим убытком закрывается.

**Comment by ivann47** [comment]
А еще подправить таблицу и сделать зеленую  линию индикатора ярче.
